coredns_version: "1.12.0"
coredns_binary_url: "https://github.com/coredns/coredns/releases/download/v{{ coredns_version }}/coredns_{{ coredns_version }}_linux_amd64.tgz"
dns_zone: "example.local"  # Default DNS zone
zone_file: "/etc/coredns/zones/{{ dns_zone }}.zone"
coredns_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"
