# description: Creates virtual machines on a KVM host.
# usage: 
#   - ansible-playbook create_vms.yaml -i inventory.yaml
#   - ansible-playbook create_vms.yaml -i inventory.yaml -l <inventory_group>
#   - ansible-playbook create_vms.yaml -i inventory.yaml -l <inventory_host>
#   - ansible-playbook create_vms.yaml -i inventory.yaml -l group -e "use_backing_file=false"
#   - ansible-playbook create_vms.yaml -i inventory.yaml -l group -e "kvmhost=x.x.x.x"
#   - ansible-playbook create_vms.yaml -i inventory.yaml -l group -e "update_dns=false"
#
# variables:
#   - use_backing_file: (bool) Whether to use a backing file for VM disks. False creates a standalone qcow2 disk image not tied to a shared backign file. 
#   - kvmhost: KVM server where VM's will be created
#
# prerequisites:
#   - KMV role
#   - Functioning KVM server. There is an install_kvm task in the kvm role.

- name: create_vms
  hosts: all  # Allows limiting with -l
  become: yes
  gather_facts: no
  vars:
    update_dns: true
    use_backing_file: true
    kvmhost: "{{ hostvars['kvm01']['ansible_host'] }}"
    ubuntu_user: darrin
    ubuntu_pass: thisok?
    ssh_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDVyvgaKoaLfRQLV1+2/UUsuJSClgL/jwXfaB0Dyp12a+LODIBjoFQTE6Cg4rJh3mpDS4WLj8XdJiHMHQPjat6wbv9nS454vLDRAYF/L0yTrazE7XhckoebuKMvFKlp7b/+mZZzEX9xdlCMUdBDD4KuYMI7PjfWGzsN8jGnG9Lk+GRc+HXexfnnY90+fob+6g55nx6U4oiIRvFvbXCo0o4vwRHnxr/RurL08T2wKD8Vnhn2gneiz96i1sgfKGbhBjJwtNaYJSHqpzNE5/3IVVjrhSX3COfWXnMWaZ18ZWZJZF3S/gvtb2ETFvLjsGxjFGuHpTOSw9w+PG5K0CTW0P6Fk1c0Ph6eDboj1uhjIcEhoR8ToZMlkII/VqNE5yJQiX5BuuFuKcn+K2SNfAvmPimigOG1E6edWlA89+xzGqC77G1myakVbW8sXsnwOu/Dp13QJvOFTT78TT6n6tk6KCJOeG4rpLoPYGFmDJliLFILsYiCz+ywy9Hvz7AQsnt5Cqs=

  pre_tasks:
    - name: Warn if no limit (-l) specified
      pause:
        prompt: "WARNING: No -l specified. This will target the entire inventory. Press ENTER to continue or Ctrl+C to cancel."
      when: ansible_limit is not defined

  tasks:
    - name: Create VMs on KVM host
      # include role module can't delegate but we can delegate an entire block to the kvmhost. all the tasks in the role must target the kvm host.
      delegate_to: "{{ kvmhost }}"
      block:
        - name: Include KVM role to create VMs
          include_role:
            name: kvm
            tasks_from: create_vm
          vars:
            disk_size: "{{ hostvars[hostname].disk_size }}"
            ram_size: "{{ hostvars[hostname].ram_size }}"
            cpu_count: "{{ hostvars[hostname].cpu_count }}"
            hostname: "{{ inventory_hostname }}"

    
    - name: Include CoreDNS role to create or update DNS record
      delegate_to: "{{ hostvars['ns01'].ansible_host }}"
      block:
        - name: Include the CoreDNS role for DNS record management
          include_role:
            name: coredns
            tasks_from: create_or_update
          vars:
            dns_zone: "{{ hostvars[inventory_hostname].dns_zone }}"
            dns_record_name: "{{ inventory_hostname }}"
            dns_record_ip: "{{ hostvars[inventory_hostname].ansible_host }}"
          when: update_dns == true
